type: object
x-stoplight:
  id: gsja17qu12o7s
title: Environment Provider
description: |-
  An API provider application for a specific environment.

  A provider is also known as a backend application, a system that hosts the API service, lying behind the SEAPIM platform.
required:
  - assetId
  - createdAt
  - updatedAt
  - environment
properties:
  assetId:
    type: string
    x-stoplight:
      id: 091ujao2fr29f
    example: '12345'
    description: 'Application asset id, as defined in the SE asset management system'
  providerUrls:
    type: array
    x-stoplight:
      id: smzl39xy0368i
    description: Provider system URL for this API
    items:
      x-stoplight:
        id: 95fhuei6eisuj
      type: string
      format: uri
  reverseProxies:
    type: array
    x-stoplight:
      id: 9jwrvebbxe6n9
    description: 'Regional reverse proxy details, if the provided is hosted in the SE private network'
    items:
      x-stoplight:
        id: adkvby7t5edx7
      type: string
  instructions:
    type: string
    x-stoplight:
      id: 4ie4b122zmxtg
    description: Extra information to help connect with a provider
  createdAt:
    $ref: ../models/CreatedAt.yaml
    description: The time this record was created
    x-stoplight:
      id: tfv08kgub32dr
  updatedAt:
    $ref: ../models/UpdatedAt.yaml
    description: The time this record was last updated
    x-stoplight:
      id: dnben192voi5u
  environment:
    $ref: ./Environment.yaml
    x-stoplight:
      id: itp0pypfvmlyi
    description: API requirements-related SEAPIM environment
